### ISSUE TITLE
Problems with podfile. 

### ISSUE THREAD

**Issue by Dylanvs19** [learn-co-curriculum/objc-palindrome-detector#2]
Hello - I've tried to complete this lab several times and I keep getting these issues (which makes it difficult to run any tests). I have tried pod install, pod update, removing Cocoapods & reinstalling. Am I doing something wrong here?

Diff: /../Podfile.lock: No such file or directory

Diff: /Manifest.lock: No such file or directory

The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Thanks!

**Comment by markedwardmurray** [comment]
Hi Dylan, I think you may have run the tests instead of running the scheme. Use `shift` `command` `k` to clean the issues and `command` `r` to run the scheme instead of the tests. I deleted the testing pods but not the config link so if you run the tests it tries to look for the pods that aren't there. That's all.

In the future, I'll notice your question sooner if you use the Ask A Question feature in learn. It also helps me find your profile faster.

**Comment by Dylanvs19** [comment]
Awesome, thanks so much Mark.
